### ISSUE TITLE
ModuleNotFoundError: No module named 'torch_lazy'

### ISSUE THREAD

**Issue by logogriph2** [huzeyann/Mem#1]
`python plmodels.py`

res

```
/home/admin2/Algonaut/dinov2/dinov2/layers/swiglu_ffn.py:43: UserWarning: xFormers is available (SwiGLU)
  warnings.warn("xFormers is available (SwiGLU)")
/home/admin2/Algonaut/dinov2/dinov2/layers/attention.py:27: UserWarning: xFormers is available (Attention)
  warnings.warn("xFormers is available (Attention)")
/home/admin2/Algonaut/dinov2/dinov2/layers/block.py:33: UserWarning: xFormers is available (Block)
  warnings.warn("xFormers is available (Block)")
Traceback (most recent call last):
  File "/home/admin2/Algonaut/MemoryEncodingModel/mem/plmodels.py", line 26, in <module>
    from neck import build_neck
  File "/home/admin2/Algonaut/MemoryEncodingModel/mem/neck.py", line 7, in <module>
    from topyneck import TopyNeck
  File "/home/admin2/Algonaut/MemoryEncodingModel/mem/topyneck.py", line 12, in <module>
    from torch_lazy.nn import LazyBatchNorm, LazyLayerNorm
ModuleNotFoundError: No module named 'torch_lazy'
```

Did you mean https://github.com/simaki/torch-lazy? (closed repo)

**Comment by huzeyann** [comment]
thank you for finding this error. the `torch_lazy` import is never used, I made a commit and deleted this line
I developed the code with docker environment, the conda env file is copied from another similar project, please notify me if there's any error with the conda env (I will not maintain the pip requirements.txt though).
